local m = require("github.com/w6xian/gua/examples/tm/test")
print("--------t.lua---------,")
print("GetNum3:" , m.GetNum3())
m.SetNum3(100)
print("SetNum3:" , 100)
print("GetNum3:" , m.GetNum3())
m.SetNum3(101)
print("SetNum3:" , 101)
print("-------t.lua----------!")