local m = require("github.com/w6xian/gua/examples/tm/test")
local tt = require("tt")
print("--------t.lua---------,")
print("GetNum3:" , m.GetNum3())
m.SetNum3(100)
print("SetNum3:" , 100)
print("GetNum3:" , m.GetNum3())
m.SetNum3(101)
print("SetNum3:" , 101)
print("-------t.lua----------!")
print("--------tt.lua---------,")
print("GetNum4:" , tt.GetNum4())
tt.SetNum4(100)
print("SetNum4:" , 100)
print("GetNum4:" , tt.GetNum4())
tt.SetNum4(101)
print("SetNum4:" , 101)
print("GetNum4:" , tt.GetNum4())